[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "nft"
  included_files = ["node_modules/pdf-parse/**", "node_modules/pdfjs-dist/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
